[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "AxiomCoreEngine"
version = "1.0.0"
description = "Scalar AI Architecture Runtime"
authors = [
    { name="Jeffrey Siergiej" }
]
requires-python = ">=3.11"
dependencies = []
