# File: .github/workflows/bandit-scan.yml
name: Bandit Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bandit:
    name: Bandit Python Security Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Bandit
      run: |
        pip install bandit

    - name: Run Bandit
      run: |
        bandit -r .
