# File: .github/workflows/manual.yml
name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Manual Run
      run: echo "This workflow was triggered manually."
