name: Manual Workflow

on:
  workflow_dispatch:

jobs:
  run-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Manual trigger confirmation
        run: echo "This manual workflow was triggered successfully."
