name: Python package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pip and dummy dependencies
      run: |
        python -m pip install --upgrade pip
        echo "# No requirements.txt yet" > dummy.txt
        echo "black" > requirements.txt
        pip install -r requirements.txt || true

    - name: Run dummy tests (always pass)
      run: |
        echo "print('Test placeholder')" > test_dummy.py
        python test_dummy.py || true
